[Service]
User=root
Group=root
ExecStart=
ExecStart=/bin/sh -c 'exec /usr/bin/promtail -config.file=/etc/promtail/config.yml -client.external-labels=server_ip=$(hostname -I | awk "{print \$1}"),host=$(hostname)'